defaults:
  - _zh
  - _claim

_transformer_model: /public/home/dzhang/pyProject/hytian/NNER_AS_PARSING_ADD_PIC_WEIBO/pretrain_model/bert_base_chinese
_use_subword: true
_use_word: true

_word_embedding: glove_zh

word_embedding:
  field: words
  normalize:
    when: begin
    method: std
  args:
    _target_: fastNLP.embeddings.StaticEmbedding
    model_dir_or_name: ${emb_mapping.${embedding._word_embedding}}
    min_freq: 2
    lower: true

bert:
  field: subwords
  requires_vocab: false
  args:
    _target_: src.modules.embeddings.TransformersEmbedding
    model: ${embedding._transformer_model}
    n_layers: 4
    n_out: 0
    requires_grad: true
    stride: 512
    pooling: mean